### PR TITLE
ftpsync verbose is determined by grunt config

### PR DESCRIPTION
**Pull request by fily55**
ftpsync.log.verbose is hard coded to true. This should really be determined by the grunt config. It is spitting out a lot of detail a regular use shouldn't display. If you want to see verbose details you should use the verbose flag.

### CODE REVIEW

**Comment by evanplaice** [comment]
Thanks for your contribution.

Quick question, what's the easiest way to set the option?

**Comment by fily55** [comment]
Hi @evanplaice,

When you run grunt [task] --v (or --verbose) you will be passing in true for this option, otherwise it is false.

Hope this helps :)

**Comment by evanplaice** [comment]
@fily55 Gotcha, so it's a global grunt option. Not something that needs to be configured specifically for `grunt-ftpsync`

I was just trying to determine whether the documentation needed an update.

**Comment by fily55** [comment]
@evanplaice - Yep, so you shouldn't have to do anything.

**Comment by evanplaice** [comment]
@fily55 Awesome! Thanks again.

**Pull request merged**
